version: '3'

services:
  db:
    image: mariadb/server:10.3
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=beny
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=intuit_schema
    ports:
      - 3306:3306
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin